/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : ConversationId,
  'lastMessage' : [] | [Message],
  'updatedAt' : Timestamp,
  'participantIds' : Array<UserId>,
}
export type ConversationId = bigint;
export interface ConversationPreview {
  'id' : ConversationId,
  'lastMessageTimestamp' : [] | [Timestamp],
  'lastMessageText' : [] | [string],
  'updatedAt' : Timestamp,
  'participantIds' : Array<UserId>,
  'participantNames' : Array<string>,
}
export interface Message {
  'id' : MessageId,
  'text' : string,
  'conversationId' : ConversationId,
  'timestamp' : Timestamp,
  'senderName' : string,
  'senderId' : UserId,
}
export type MessageId = bigint;
export type PresenceStatus = { 'offline' : null } |
  { 'online' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserPresence {
  'status' : PresenceStatus,
  'userId' : UserId,
  'lastSeen' : Timestamp,
}
export interface UserProfile {
  'id' : UserId,
  'username' : string,
  'displayName' : string,
  'avatarUrl' : [] | [string],
}
export interface _SERVICE {
  'getBulkPresence' : ActorMethod<[Array<UserId>], Array<UserPresence>>,
  'getConversation' : ActorMethod<[ConversationId], [] | [Conversation]>,
  'getMessages' : ActorMethod<[ConversationId], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getOrCreateConversation' : ActorMethod<[UserId], ConversationId>,
  'getTypingUsers' : ActorMethod<[ConversationId, UserId], Array<UserId>>,
  'getUserPresence' : ActorMethod<[UserId], UserPresence>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'listConversations' : ActorMethod<[], Array<ConversationPreview>>,
  'registerUser' : ActorMethod<[string, string], UserProfile>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[ConversationId, string], Message>,
  'setOffline' : ActorMethod<[], undefined>,
  'setOnline' : ActorMethod<[], undefined>,
  'setTyping' : ActorMethod<[ConversationId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];