/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const PresenceStatus = IDL.Variant({
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserPresence = IDL.Record({
  'status' : PresenceStatus,
  'userId' : UserId,
  'lastSeen' : Timestamp,
});
export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'conversationId' : ConversationId,
  'timestamp' : Timestamp,
  'senderName' : IDL.Text,
  'senderId' : UserId,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'lastMessage' : IDL.Opt(Message),
  'updatedAt' : Timestamp,
  'participantIds' : IDL.Vec(UserId),
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const ConversationPreview = IDL.Record({
  'id' : ConversationId,
  'lastMessageTimestamp' : IDL.Opt(Timestamp),
  'lastMessageText' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'participantIds' : IDL.Vec(UserId),
  'participantNames' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getBulkPresence' : IDL.Func(
      [IDL.Vec(UserId)],
      [IDL.Vec(UserPresence)],
      ['query'],
    ),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
  'getTypingUsers' : IDL.Func(
      [ConversationId, UserId],
      [IDL.Vec(UserId)],
      ['query'],
    ),
  'getUserPresence' : IDL.Func([UserId], [UserPresence], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationPreview)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
  'setOffline' : IDL.Func([], [], []),
  'setOnline' : IDL.Func([], [], []),
  'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const PresenceStatus = IDL.Variant({
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserPresence = IDL.Record({
    'status' : PresenceStatus,
    'userId' : UserId,
    'lastSeen' : Timestamp,
  });
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'conversationId' : ConversationId,
    'timestamp' : Timestamp,
    'senderName' : IDL.Text,
    'senderId' : UserId,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'lastMessage' : IDL.Opt(Message),
    'updatedAt' : Timestamp,
    'participantIds' : IDL.Vec(UserId),
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const ConversationPreview = IDL.Record({
    'id' : ConversationId,
    'lastMessageTimestamp' : IDL.Opt(Timestamp),
    'lastMessageText' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'participantIds' : IDL.Vec(UserId),
    'participantNames' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getBulkPresence' : IDL.Func(
        [IDL.Vec(UserId)],
        [IDL.Vec(UserPresence)],
        ['query'],
      ),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
    'getTypingUsers' : IDL.Func(
        [ConversationId, UserId],
        [IDL.Vec(UserId)],
        ['query'],
      ),
    'getUserPresence' : IDL.Func([UserId], [UserPresence], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPreview)],
        ['query'],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
    'setOffline' : IDL.Func([], [], []),
    'setOnline' : IDL.Func([], [], []),
    'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };