/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface UserPresence {
    status: PresenceStatus;
    userId: UserId;
    lastSeen: Timestamp;
}
export type Timestamp = bigint;
export type MessageId = bigint;
export interface Message {
    id: MessageId;
    text: string;
    conversationId: ConversationId;
    timestamp: Timestamp;
    senderName: string;
    senderId: UserId;
}
export interface ConversationPreview {
    id: ConversationId;
    lastMessageTimestamp?: Timestamp;
    lastMessageText?: string;
    updatedAt: Timestamp;
    participantIds: Array<UserId>;
    participantNames: Array<string>;
}
export interface Conversation {
    id: ConversationId;
    lastMessage?: Message;
    updatedAt: Timestamp;
    participantIds: Array<UserId>;
}
export interface UserProfile {
    id: UserId;
    username: string;
    displayName: string;
    avatarUrl?: string;
}
export type ConversationId = bigint;
export enum PresenceStatus {
    offline = "offline",
    online = "online"
}
export interface backendInterface {
    getBulkPresence(userIds: Array<UserId>): Promise<Array<UserPresence>>;
    getConversation(conversationId: ConversationId): Promise<Conversation | null>;
    getMessages(conversationId: ConversationId): Promise<Array<Message>>;
    getMyProfile(): Promise<UserProfile | null>;
    getOrCreateConversation(otherUserId: UserId): Promise<ConversationId>;
    getTypingUsers(conversationId: ConversationId, excludeUserId: UserId): Promise<Array<UserId>>;
    getUserPresence(userId: UserId): Promise<UserPresence>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    listConversations(): Promise<Array<ConversationPreview>>;
    registerUser(username: string, displayName: string): Promise<UserProfile>;
    searchUsers(searchTerm: string): Promise<Array<UserProfile>>;
    sendMessage(conversationId: ConversationId, text: string): Promise<Message>;
    setOffline(): Promise<void>;
    setOnline(): Promise<void>;
    setTyping(conversationId: ConversationId, isTyping: boolean): Promise<void>;
}
import type { Conversation as _Conversation, ConversationId as _ConversationId, ConversationPreview as _ConversationPreview, Message as _Message, PresenceStatus as _PresenceStatus, Timestamp as _Timestamp, UserId as _UserId, UserPresence as _UserPresence, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getBulkPresence(arg0: Array<UserId>): Promise<Array<UserPresence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBulkPresence(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBulkPresence(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: ConversationId): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: ConversationId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateConversation(arg0: UserId): Promise<ConversationId> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateConversation(arg0);
            return result;
        }
    }
    async getTypingUsers(arg0: ConversationId, arg1: UserId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTypingUsers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTypingUsers(arg0, arg1);
            return result;
        }
    }
    async getUserPresence(arg0: UserId): Promise<UserPresence> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPresence(arg0);
                return from_candid_UserPresence_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPresence(arg0);
            return from_candid_UserPresence_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConversations(): Promise<Array<ConversationPreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: ConversationId, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setOffline(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOffline();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOffline();
            return result;
        }
    }
    async setOnline(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOnline();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOnline();
            return result;
        }
    }
    async setTyping(arg0: ConversationId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTyping(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTyping(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ConversationPreview_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationPreview): ConversationPreview {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PresenceStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PresenceStatus): PresenceStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserPresence_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPresence): UserPresence {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : from_candid_Conversation_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    displayName: string;
    avatarUrl: [] | [string];
}): {
    id: UserId;
    username: string;
    displayName: string;
    avatarUrl?: string;
} {
    return {
        id: value.id,
        username: value.username,
        displayName: value.displayName,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    lastMessageTimestamp: [] | [_Timestamp];
    lastMessageText: [] | [string];
    updatedAt: _Timestamp;
    participantIds: Array<_UserId>;
    participantNames: Array<string>;
}): {
    id: ConversationId;
    lastMessageTimestamp?: Timestamp;
    lastMessageText?: string;
    updatedAt: Timestamp;
    participantIds: Array<UserId>;
    participantNames: Array<string>;
} {
    return {
        id: value.id,
        lastMessageTimestamp: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.lastMessageTimestamp)),
        lastMessageText: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastMessageText)),
        updatedAt: value.updatedAt,
        participantIds: value.participantIds,
        participantNames: value.participantNames
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PresenceStatus;
    userId: _UserId;
    lastSeen: _Timestamp;
}): {
    status: PresenceStatus;
    userId: UserId;
    lastSeen: Timestamp;
} {
    return {
        status: from_candid_PresenceStatus_n4(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        lastSeen: value.lastSeen
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    lastMessage: [] | [_Message];
    updatedAt: _Timestamp;
    participantIds: Array<_UserId>;
}): {
    id: ConversationId;
    lastMessage?: Message;
    updatedAt: Timestamp;
    participantIds: Array<UserId>;
} {
    return {
        id: value.id,
        lastMessage: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.lastMessage)),
        updatedAt: value.updatedAt,
        participantIds: value.participantIds
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offline: null;
} | {
    online: null;
}): PresenceStatus {
    return "offline" in value ? PresenceStatus.offline : "online" in value ? PresenceStatus.online : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPresence>): Array<UserPresence> {
    return value.map((x)=>from_candid_UserPresence_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationPreview>): Array<ConversationPreview> {
    return value.map((x)=>from_candid_ConversationPreview_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
